<?php

namespace Database\Seeders;

use App\Models\StargazingSpot;
use Illuminate\Database\Seeder;

class StargazingSpotsSeeder extends Seeder
{
    public function run(): void
    {
        $spots = [
            // ==================== UNITED KINGDOM (25) ====================
            [
                'name' => 'Kielder Observatory & Forest Park',
                'slug' => 'kielder-observatory',
                'country' => 'United Kingdom',
                'region' => 'Northumberland',
                'latitude' => 55.2333,
                'longitude' => -2.5833,
                'elevation' => 360,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'England\'s premier dark sky discovery site, situated deep within the 250-square-mile Northumberland International Dark Sky Park with pristine Bortle 2 skies.',
            ],
            [
                'name' => 'Brecon Beacons (Bannau Brycheiniog)',
                'slug' => 'brecon-beacons',
                'country' => 'United Kingdom',
                'region' => 'Wales',
                'latitude' => 51.8833,
                'longitude' => -3.4333,
                'elevation' => 450,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'Wales\' first International Dark Sky Reserve, offering expansive southern horizons over the Usk Reservoir, Crai Reservoir, and Llangorse Lake.',
            ],
            [
                'name' => 'Galloway Forest Park',
                'slug' => 'galloway-forest-park',
                'country' => 'United Kingdom',
                'region' => 'Scotland',
                'latitude' => 55.0833,
                'longitude' => -4.4167,
                'elevation' => 280,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'The UK\'s first designated Dark Sky Park, encompassing 300 square miles of rugged Scottish wilderness with negligible light pollution.',
            ],
            [
                'name' => 'Exmoor National Park',
                'slug' => 'exmoor-national-park',
                'country' => 'United Kingdom',
                'region' => 'Devon & Somerset',
                'latitude' => 51.1333,
                'longitude' => -3.6500,
                'elevation' => 420,
                'bortle_class' => 2,
                'dark_sky_status' => 'Europe\'s First International Dark Sky Reserve',
                'description' => 'Home to Dunkery Beacon and Brendon Common, offering sensational coastal and moorland vistas with crystal clear night skies.',
            ],
            [
                'name' => 'North York Moors',
                'slug' => 'north-york-moors',
                'country' => 'United Kingdom',
                'region' => 'Yorkshire',
                'latitude' => 54.3667,
                'longitude' => -0.8833,
                'elevation' => 310,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'Expansive heather moorland with dark sky discovery sites at Sutton Bank and Danby Lodge National Park Centre.',
            ],
            [
                'name' => 'Yorkshire Dales (Hawes & Tan Hill)',
                'slug' => 'yorkshire-dales',
                'country' => 'United Kingdom',
                'region' => 'Yorkshire',
                'latitude' => 54.3000,
                'longitude' => -2.2000,
                'elevation' => 528,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'High limestone plateaus and dramatic peaks including Tan Hill and Buckden, showcasing the Milky Way arching across unpolluted skies.',
            ],
            [
                'name' => 'Elan Valley',
                'slug' => 'elan-valley',
                'country' => 'United Kingdom',
                'region' => 'Mid Wales',
                'latitude' => 52.2667,
                'longitude' => -3.6167,
                'elevation' => 380,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => '72 square miles of Welsh Victorian reservoirs and wild Cambrian mountains, recognized for exceptionally dark and transparent skies.',
            ],
            [
                'name' => 'Snowdonia (Eryri National Park)',
                'slug' => 'eryri-snowdonia',
                'country' => 'United Kingdom',
                'region' => 'North Wales',
                'latitude' => 53.0667,
                'longitude' => -3.9833,
                'elevation' => 500,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'Majestic glacial valleys and dramatic peaks like Llyn y Dywarchen and Llyn Geirionydd offering mirror-like reflections of deep space.',
            ],
            [
                'name' => 'Cairngorms Dark Sky Park (Tomintoul & Glenlivet)',
                'slug' => 'cairngorms-tomintoul',
                'country' => 'United Kingdom',
                'region' => 'Scottish Highlands',
                'latitude' => 57.3167,
                'longitude' => -3.3833,
                'elevation' => 350,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'The most northerly International Dark Sky Park in the world, with frequent opportunities to observe the Aurora Borealis against truly dark skies.',
            ],
            [
                'name' => 'Isle of Sark',
                'slug' => 'isle-of-sark',
                'country' => 'United Kingdom',
                'region' => 'Channel Islands',
                'latitude' => 49.4333,
                'longitude' => -2.3667,
                'elevation' => 100,
                'bortle_class' => 2,
                'dark_sky_status' => 'World\'s First Dark Sky Island',
                'description' => 'With no cars and no public street lighting, this tiny Channel Island offers extraordinary uninterrupted sea-level stargazing.',
            ],
            [
                'name' => 'Isle of Coll',
                'slug' => 'isle-of-coll',
                'country' => 'United Kingdom',
                'region' => 'Inner Hebrides, Scotland',
                'latitude' => 56.6333,
                'longitude' => -6.5500,
                'elevation' => 40,
                'bortle_class' => 1,
                'dark_sky_status' => 'IDA Dark Sky Island',
                'description' => 'One of the darkest inhabited islands in Europe, surrounded by the Atlantic Ocean with zero light pollution and Bortle 1 skies.',
            ],
            [
                'name' => 'Bodmin Moor & Carnglaze',
                'slug' => 'bodmin-moor',
                'country' => 'United Kingdom',
                'region' => 'Cornwall',
                'latitude' => 50.5500,
                'longitude' => -4.6167,
                'elevation' => 290,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Landscape',
                'description' => 'Atmospheric Cornish granite landscape with dark sky vantage points around Minions, Crowdy Reservoir, and Rough Tor.',
            ],
            [
                'name' => 'South Downs National Park',
                'slug' => 'south-downs-national-park',
                'country' => 'United Kingdom',
                'region' => 'Sussex & Hampshire',
                'latitude' => 50.9833,
                'longitude' => -0.6333,
                'elevation' => 210,
                'bortle_class' => 4,
                'dark_sky_status' => 'IDA International Dark Sky Reserve (Moore\'s Reserve)',
                'description' => 'Named in honor of Sir Patrick Moore, offering accessible dark sky discovery sites within reach of southern England (e.g. Devil\'s Dyke, Bignor Hill).',
            ],
            [
                'name' => 'Cranborne Chase',
                'slug' => 'cranborne-chase',
                'country' => 'United Kingdom',
                'region' => 'Dorset, Wiltshire & Hampshire',
                'latitude' => 50.9833,
                'longitude' => -2.0500,
                'elevation' => 190,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'Rolling chalk downland and ancient woodlands with exceptionally dark skies across the heart of rural Wessex.',
            ],
            [
                'name' => 'Northumberland Coast (Embleton & Dunstanburgh)',
                'slug' => 'northumberland-coast',
                'country' => 'United Kingdom',
                'region' => 'Northumberland',
                'latitude' => 55.4833,
                'longitude' => -1.6000,
                'elevation' => 20,
                'bortle_class' => 3,
                'dark_sky_status' => 'National Landscape Dark Sky Area',
                'description' => 'Dramatic North Sea coastal scenery beneath medieval ruins, with dark eastern horizons ideal for ocean astro-imaging and satellite tracking.',
            ],
            [
                'name' => 'St Agnes & Isles of Scilly',
                'slug' => 'st-agnes-scilly',
                'country' => 'United Kingdom',
                'region' => 'Cornwall',
                'latitude' => 49.8917,
                'longitude' => -6.3417,
                'elevation' => 25,
                'bortle_class' => 2,
                'dark_sky_status' => 'Dark Sky Community',
                'description' => 'The southwestern-most inhabited island of the UK, jutting 28 miles into the Atlantic with pitch black ocean skies in every direction.',
            ],
            [
                'name' => 'Lindisfarne (Holy Island)',
                'slug' => 'lindisfarne-holy-island',
                'country' => 'United Kingdom',
                'region' => 'Northumberland',
                'latitude' => 55.6780,
                'longitude' => -1.7980,
                'elevation' => 15,
                'bortle_class' => 3,
                'dark_sky_status' => 'Protected Dark Coastal Reserve',
                'description' => 'Tidal island steeped in history, offering dark night skies framed by the Lindisfarne Priory ruins and castle silhouette.',
            ],
            [
                'name' => 'Llyn y Fan Fach (Black Mountain)',
                'slug' => 'llyn-y-fan-fach',
                'country' => 'United Kingdom',
                'region' => 'Carmarthenshire, Wales',
                'latitude' => 51.8790,
                'longitude' => -3.7690,
                'elevation' => 510,
                'bortle_class' => 2,
                'dark_sky_status' => 'Dark Sky Discovery Core Site',
                'description' => 'Enchanting glacial tarn nestled beneath dramatic precipitous escarpments with virtually zero southern horizon light interference.',
            ],
            [
                'name' => 'Loch Doon & Scottish Dark Sky Observatory Site',
                'slug' => 'loch-doon',
                'country' => 'United Kingdom',
                'region' => 'Ayrshire, Scotland',
                'latitude' => 55.2500,
                'longitude' => -4.3833,
                'elevation' => 230,
                'bortle_class' => 2,
                'dark_sky_status' => 'Core Dark Sky Reserve',
                'description' => 'Sprawling loch in the Galloway Hills providing mirror-flat water foregrounds beneath dense starfields of the Milky Way core.',
            ],
            [
                'name' => 'Clwydian Range & Dee Valley',
                'slug' => 'clwydian-range',
                'country' => 'United Kingdom',
                'region' => 'Denbighshire, Wales',
                'latitude' => 53.1500,
                'longitude' => -3.2833,
                'elevation' => 450,
                'bortle_class' => 3,
                'dark_sky_status' => 'Designated National Landscape Dark Sky Site',
                'description' => 'High vantage points at Moel Famau overlooking northern Wales, offering wide panoramic stargazing and transit tracking.',
            ],
            [
                'name' => 'Dorset Jurassic Coast (Kimmeridge Bay)',
                'slug' => 'kimmeridge-bay-dorset',
                'country' => 'United Kingdom',
                'region' => 'Dorset',
                'latitude' => 50.6080,
                'longitude' => -2.1280,
                'elevation' => 30,
                'bortle_class' => 3,
                'dark_sky_status' => 'Protected Heritage Coast',
                'description' => 'Famous fossil coast with south-facing ocean horizons and Clavell Tower, prized by British astrophotographers for core Milky Way tracking.',
            ],
            [
                'name' => 'Shropshire Hills (Long Mynd & Stiperstones)',
                'slug' => 'shropshire-hills-long-mynd',
                'country' => 'United Kingdom',
                'region' => 'Shropshire',
                'latitude' => 52.5500,
                'longitude' => -2.8667,
                'elevation' => 490,
                'bortle_class' => 3,
                'dark_sky_status' => 'Dark Sky Discovery Site',
                'description' => 'Dramatic heather-clad plateau rising above the Shropshire plain with 360-degree horizon exposure.',
            ],
            [
                'name' => 'Pembrokeshire Coast (St David\'s Head & Marloes)',
                'slug' => 'pembrokeshire-coast',
                'country' => 'United Kingdom',
                'region' => 'Pembrokeshire, Wales',
                'latitude' => 51.7280,
                'longitude' => -5.2030,
                'elevation' => 45,
                'bortle_class' => 2,
                'dark_sky_status' => 'Coastal Dark Sky Sanctuary',
                'description' => 'Far western Welsh peninsula jutting into the Irish Sea with dark coastal skies and rugged offshore island silhouettes.',
            ],
            [
                'name' => 'Isle of Wight (Military Road & Compton Bay)',
                'slug' => 'isle-of-wight-compton',
                'country' => 'United Kingdom',
                'region' => 'Isle of Wight',
                'latitude' => 50.6550,
                'longitude' => -1.4880,
                'elevation' => 60,
                'bortle_class' => 3,
                'dark_sky_status' => 'Heritage Dark Coastline',
                'description' => 'Southwestern coastline of the island looking out toward the English Channel with very little artificial light pollution.',
            ],
            [
                'name' => 'Glen Affric',
                'slug' => 'glen-affric',
                'country' => 'United Kingdom',
                'region' => 'Highlands, Scotland',
                'latitude' => 57.2667,
                'longitude' => -4.9500,
                'elevation' => 260,
                'bortle_class' => 1,
                'dark_sky_status' => 'Caledonian Dark Sky Wilderness',
                'description' => 'Often described as Scotland\'s most beautiful glen, surrounded by ancient Caledonian pines under untamed Bortle 1 skies.',
            ],

            // ==================== EUROPE (25) ====================
            [
                'name' => 'Pic du Midi Observatory',
                'slug' => 'pic-du-midi',
                'country' => 'France',
                'region' => 'Pyrenees',
                'latitude' => 42.9369,
                'longitude' => 0.1411,
                'elevation' => 2877,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'Iconic mountaintop high-altitude observatory above the clouds in the French Pyrenees, revered for astronomical research and astrophotography.',
            ],
            [
                'name' => 'Teide Observatory & National Park',
                'slug' => 'teide-observatory-tenerife',
                'country' => 'Spain',
                'region' => 'Canary Islands (Tenerife)',
                'latitude' => 28.3000,
                'longitude' => -16.5100,
                'elevation' => 2390,
                'bortle_class' => 1,
                'dark_sky_status' => 'Starlight Tourist Destination & Reserve',
                'description' => 'One of the world\'s top three observing sites. Located inside the crater caldera above the Atlantic temperature inversion layer.',
            ],
            [
                'name' => 'Roque de los Muchachos (La Palma)',
                'slug' => 'roque-de-los-muchachos',
                'country' => 'Spain',
                'region' => 'Canary Islands (La Palma)',
                'latitude' => 28.7569,
                'longitude' => -17.8817,
                'elevation' => 2426,
                'bortle_class' => 1,
                'dark_sky_status' => 'World Starlight Reserve',
                'description' => 'Protected by the pioneering Spanish Sky Law since 1988, hosting Europe\'s flagship astronomical research telescopes with Bortle 1 clarity.',
            ],
            [
                'name' => 'Alqueva Dark Sky Reserve',
                'slug' => 'alqueva-dark-sky-reserve',
                'country' => 'Portugal',
                'region' => 'Alentejo',
                'latitude' => 38.2000,
                'longitude' => -7.4833,
                'elevation' => 180,
                'bortle_class' => 2,
                'dark_sky_status' => 'World\'s First Starlight Tourism Destination',
                'description' => 'Spanning over 3,000 square kilometers around Lake Alqueva, blessed with over 280 clear nights a year and remarkably transparent skies.',
            ],
            [
                'name' => 'Montsec Astronomical Park',
                'slug' => 'montsec-astronomical-park',
                'country' => 'Spain',
                'region' => 'Catalonia',
                'latitude' => 42.0250,
                'longitude' => 0.7300,
                'elevation' => 1570,
                'bortle_class' => 2,
                'dark_sky_status' => 'Starlight Reserve & Tourist Destination',
                'description' => 'Catalan mountain range renowned across southern Europe for atmospheric stability and low humidity, shielding it from coastal light.',
            ],
            [
                'name' => 'Sierra de Gredos Dark Sky Park',
                'slug' => 'sierra-de-gredos',
                'country' => 'Spain',
                'region' => 'Castile and León',
                'latitude' => 40.2500,
                'longitude' => -5.2500,
                'elevation' => 1650,
                'bortle_class' => 2,
                'dark_sky_status' => 'Starlight Dark Sky Reserve',
                'description' => 'Granite mountain mass in central Spain offering elevation and low artificial light, ideal for deep sky astrophotography.',
            ],
            [
                'name' => 'Kerry International Dark Sky Reserve',
                'slug' => 'kerry-dark-sky-reserve',
                'country' => 'Ireland',
                'region' => 'County Kerry',
                'latitude' => 51.8500,
                'longitude' => -10.1500,
                'elevation' => 120,
                'bortle_class' => 1,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Reserve',
                'description' => 'Bounded by the Atlantic Ocean and the Iveragh Peninsula mountains, this is the only Gold Tier Reserve in the Northern Hemisphere outside parks.',
            ],
            [
                'name' => 'Mayo Dark Sky Park (Ballycroy)',
                'slug' => 'mayo-dark-sky-park',
                'country' => 'Ireland',
                'region' => 'County Mayo',
                'latitude' => 54.0167,
                'longitude' => -9.7000,
                'elevation' => 90,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'Unspoiled Atlantic blanket bog and the Nephin Beg mountain range, shielding observers completely from urban light domes.',
            ],
            [
                'name' => 'Westhavelland Nature Park',
                'slug' => 'westhavelland-nature-park',
                'country' => 'Germany',
                'region' => 'Brandenburg',
                'latitude' => 52.7000,
                'longitude' => 12.3500,
                'elevation' => 35,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'Germany\'s first Dark Sky Reserve, situated in the sprawling wetlands of the Havel river just 70km west of Berlin.',
            ],
            [
                'name' => 'Rhön Biosphere Reserve (Sternenpark Rhön)',
                'slug' => 'sternenpark-rhoen',
                'country' => 'Germany',
                'region' => 'Bavaria, Hesse & Thuringia',
                'latitude' => 50.4833,
                'longitude' => 9.9833,
                'elevation' => 950,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'The "Land of Open Horizons" with dark volcanic summits like the Wasserkuppe and Hohe Geba offering unobstructed 360-degree vistas.',
            ],
            [
                'name' => 'Eifel National Park (Sternenpark Eifel)',
                'slug' => 'eifel-national-park',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 50.5833,
                'longitude' => 6.4500,
                'elevation' => 500,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => '110 square kilometers of protected oak and beech forests in western Germany near the Belgian border.',
            ],
            [
                'name' => 'Cévennes National Park',
                'slug' => 'cevennes-national-park',
                'country' => 'France',
                'region' => 'Occitanie',
                'latitude' => 44.3333,
                'longitude' => 3.6667,
                'elevation' => 1200,
                'bortle_class' => 2,
                'dark_sky_status' => 'Largest Dark Sky Reserve in Europe',
                'description' => 'Covering over 3,500 km² across the limestone Causses and Mont Lozère, recognized as Europe\'s largest dark sky reserve.',
            ],
            [
                'name' => 'Millevaches Regional Natural Park',
                'slug' => 'millevaches-dark-sky-reserve',
                'country' => 'France',
                'region' => 'Nouvelle-Aquitaine',
                'latitude' => 45.6667,
                'longitude' => 1.9500,
                'elevation' => 850,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Reserve',
                'description' => 'High granite plateau in the Massif Central known for clean air, peat bogs, and pristine Bortle 2 night skies.',
            ],
            [
                'name' => 'Haute-Provence Observatory (OHP)',
                'slug' => 'haute-provence-observatory',
                'country' => 'France',
                'region' => 'Provence-Alpes-Côte d\'Azur',
                'latitude' => 43.9308,
                'longitude' => 5.7133,
                'elevation' => 650,
                'bortle_class' => 3,
                'dark_sky_status' => 'Historic Astronomical Heritage Site',
                'description' => 'Where the first exoplanet orbiting a main-sequence star (51 Pegasi b) was discovered in 1995, famed for stable atmospheric seeing.',
            ],
            [
                'name' => 'Zselic National Landscape Protection Area',
                'slug' => 'zselic-starry-sky-park',
                'country' => 'Hungary',
                'region' => 'Somogy',
                'latitude' => 46.2333,
                'longitude' => 17.7667,
                'elevation' => 220,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'One of the first Dark Sky Parks in Europe, featuring an astronomical public observatory and planetarium amid dense oak woodlands.',
            ],
            [
                'name' => 'Bükk National Park (Bükki Csillagpark)',
                'slug' => 'bukk-national-park',
                'country' => 'Hungary',
                'region' => 'Northern Hungary',
                'latitude' => 48.0667,
                'longitude' => 20.5167,
                'elevation' => 680,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Karst mountain plateau offering clear mountain air and dark skies in northern Hungary.',
            ],
            [
                'name' => 'Poloniny Dark Sky Park',
                'slug' => 'poloniny-dark-sky-park',
                'country' => 'Slovakia',
                'region' => 'Prešov Region',
                'latitude' => 49.0833,
                'longitude' => 22.4500,
                'elevation' => 700,
                'bortle_class' => 2,
                'dark_sky_status' => 'Dark Sky Park (UNESCO Primeval Beech Forests)',
                'description' => 'Located at the tri-border of Slovakia, Poland, and Ukraine; one of the least populated and darkest regions in Central Europe.',
            ],
            [
                'name' => 'Izera Dark-Sky Park',
                'slug' => 'izera-dark-sky-park',
                'country' => 'Poland & Czech Republic',
                'region' => 'Jizera Mountains',
                'latitude' => 50.8500,
                'longitude' => 15.3500,
                'elevation' => 840,
                'bortle_class' => 3,
                'dark_sky_status' => 'Cross-Border Dark-Sky Park',
                'description' => 'First cross-border dark-sky park in Europe, founded jointly by Polish and Czech astronomers.',
            ],
            [
                'name' => 'Lauwersmeer National Park',
                'slug' => 'lauwersmeer-national-park',
                'country' => 'Netherlands',
                'region' => 'Groningen & Friesland',
                'latitude' => 53.3667,
                'longitude' => 6.2000,
                'elevation' => 1,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'A reclaimed former sea inlet in the north of the Netherlands offering one of the rarest truly dark refuges in the Benelux region.',
            ],
            [
                'name' => 'De Boschplaat (Terschelling)',
                'slug' => 'boschplaat-terschelling',
                'country' => 'Netherlands',
                'region' => 'Friesland',
                'latitude' => 53.4333,
                'longitude' => 5.4667,
                'elevation' => 5,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Nature reserve spanning the eastern half of the Wadden Sea island of Terschelling, looking over dark North Sea waters.',
            ],
            [
                'name' => 'Dolomites (Tre Cime di Lavaredo)',
                'slug' => 'tre-cime-dolomites',
                'country' => 'Italy',
                'region' => 'South Tyrol & Veneto',
                'latitude' => 46.6186,
                'longitude' => 12.3028,
                'elevation' => 2320,
                'bortle_class' => 2,
                'dark_sky_status' => 'Alpine Dark Sky Haven',
                'description' => 'Breathtaking towering limestone battlement peaks rising above the light dome of the Po valley into crystal-clear alpine skies.',
            ],
            [
                'name' => 'Foreste Casentinesi National Park',
                'slug' => 'foreste-casentinesi',
                'country' => 'Italy',
                'region' => 'Tuscany & Emilia-Romagna',
                'latitude' => 43.8667,
                'longitude' => 11.7500,
                'elevation' => 1100,
                'bortle_class' => 3,
                'dark_sky_status' => 'Apennine Dark Sky Oasis',
                'description' => 'Ancient Apennine beech and fir forests buffering observers from Florence and Bologna light pollution.',
            ],
            [
                'name' => 'Sierra Nevada Astronomical Observatory (OSN)',
                'slug' => 'sierra-nevada-observatory',
                'country' => 'Spain',
                'region' => 'Andalusia',
                'latitude' => 37.0642,
                'longitude' => -3.3847,
                'elevation' => 2896,
                'bortle_class' => 2,
                'dark_sky_status' => 'High Alpine Observatory Reserve',
                'description' => 'Located near the Veleta peak in southern Spain, offering crisp high-altitude clarity above Mediterranean marine fog.',
            ],
            [
                'name' => 'Kozjansko & Triglav Mountain Sanctuaries',
                'slug' => 'triglav-national-park',
                'country' => 'Slovenia',
                'region' => 'Julian Alps',
                'latitude' => 46.3800,
                'longitude' => 13.8400,
                'elevation' => 1800,
                'bortle_class' => 2,
                'dark_sky_status' => 'Alpine Dark Sky Sanctuary',
                'description' => 'Slovenia\'s sole national park in the Julian Alps, providing unblemished alpine nightscapes and deep-sky visibility.',
            ],
            [
                'name' => 'Møn and Nyord Dark Sky Park',
                'slug' => 'moen-and-nyord-denmark',
                'country' => 'Denmark',
                'region' => 'Zealand',
                'latitude' => 54.9833,
                'longitude' => 12.5333,
                'elevation' => 70,
                'bortle_class' => 2,
                'dark_sky_status' => 'First Dark Sky Park & Community in the Nordic Region',
                'description' => 'Danish Baltic Sea islands famous for dramatic white chalk cliffs (Møns Klint) and virtually unpolluted marine skies.',
            ],

            // ==================== NORTH AMERICA / USA (30) ====================
            [
                'name' => 'Cherry Springs State Park',
                'slug' => 'cherry-springs-state-park',
                'country' => 'United States',
                'region' => 'Pennsylvania',
                'latitude' => 41.6628,
                'longitude' => -77.8236,
                'elevation' => 701,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'The crown jewel of East Coast astronomy. Situated on an 82-acre plateau surrounded by the 262,000-acre Susquehannock State Forest.',
            ],
            [
                'name' => 'Big Bend National Park',
                'slug' => 'big-bend-national-park',
                'country' => 'United States',
                'region' => 'Texas',
                'latitude' => 29.2500,
                'longitude' => -103.2500,
                'elevation' => 850,
                'bortle_class' => 1,
                'dark_sky_status' => 'IDA International Dark Sky Park (Gold Tier)',
                'description' => 'Has the lowest measure of light pollution of any National Park in the lower 48 states, offering Bortle 1 skies along the Rio Grande.',
            ],
            [
                'name' => 'Death Valley National Park',
                'slug' => 'death-valley-national-park',
                'country' => 'United States',
                'region' => 'California & Nevada',
                'latitude' => 36.5323,
                'longitude' => -116.9325,
                'elevation' => -50,
                'bortle_class' => 1,
                'dark_sky_status' => 'Largest Dark Sky Park in the US (Gold Tier)',
                'description' => 'Over 3 million acres of designated wilderness with extreme low humidity and vast desert horizons at Harmony Borax Works and Badwater Basin.',
            ],
            [
                'name' => 'Central Idaho Dark Sky Reserve',
                'slug' => 'central-idaho-dark-sky-reserve',
                'country' => 'United States',
                'region' => 'Idaho',
                'latitude' => 44.0000,
                'longitude' => -114.8000,
                'elevation' => 2000,
                'bortle_class' => 2,
                'dark_sky_status' => 'First Gold Tier Dark Sky Reserve in the US',
                'description' => '1,400 square miles of pristine Sawtooth and Pioneer mountain wilderness with crystalline high-elevation transparency.',
            ],
            [
                'name' => 'Natural Bridges National Monument',
                'slug' => 'natural-bridges-national-monument',
                'country' => 'United States',
                'region' => 'Utah',
                'latitude' => 37.6000,
                'longitude' => -110.0167,
                'elevation' => 1980,
                'bortle_class' => 2,
                'dark_sky_status' => 'World\'s First International Dark Sky Park (2007)',
                'description' => 'Where the IDA certification program was born. Framed by majestic natural stone spans like Owachomo Bridge beneath brilliant star clouds.',
            ],
            [
                'name' => 'Great Basin National Park',
                'slug' => 'great-basin-national-park',
                'country' => 'United States',
                'region' => 'Nevada',
                'latitude' => 38.9833,
                'longitude' => -114.3000,
                'elevation' => 2400,
                'bortle_class' => 1,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Remote Nevada basin with Wheeler Peak rising above 13,000 ft and some of the cleanest, lowest light-polluted air in North America.',
            ],
            [
                'name' => 'Joshua Tree National Park',
                'slug' => 'joshua-tree-national-park',
                'country' => 'United States',
                'region' => 'California',
                'latitude' => 33.8734,
                'longitude' => -115.9010,
                'elevation' => 1000,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Iconic desert landscapes and bizarre Joshua tree silhouettes framed by brilliant night skies across Cottonwood and Pinto Basin.',
            ],
            [
                'name' => 'Headlands International Dark Sky Park',
                'slug' => 'headlands-dark-sky-park',
                'country' => 'United States',
                'region' => 'Michigan',
                'latitude' => 45.7760,
                'longitude' => -84.7860,
                'elevation' => 185,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Located on the tip of the Lower Peninsula along Lake Michigan, renowned for pristine northern horizon views of the Northern Lights.',
            ],
            [
                'name' => 'Stephen C. Foster State Park (Okefenokee)',
                'slug' => 'stephen-c-foster-state-park',
                'country' => 'United States',
                'region' => 'Georgia',
                'latitude' => 30.8250,
                'longitude' => -82.3650,
                'elevation' => 35,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park (Gold Tier)',
                'description' => 'Deep in the heart of the 402,000-acre Okefenokee Swamp, one of the darkest pockets in the southeastern United States.',
            ],
            [
                'name' => 'Cosmic Campground International Dark Sky Sanctuary',
                'slug' => 'cosmic-campground-new-mexico',
                'country' => 'United States',
                'region' => 'New Mexico',
                'latitude' => 33.4792,
                'longitude' => -108.9228,
                'elevation' => 1630,
                'bortle_class' => 1,
                'dark_sky_status' => 'First International Dark Sky Sanctuary in North America',
                'description' => 'Located in the Gila National Forest, more than 40 miles from any significant artificial light source with Bortle 1 conditions.',
            ],
            [
                'name' => 'Kissimmee Prairie Preserve State Park',
                'slug' => 'kissimmee-prairie-preserve',
                'country' => 'United States',
                'region' => 'Florida',
                'latitude' => 27.5850,
                'longitude' => -81.0480,
                'elevation' => 20,
                'bortle_class' => 3,
                'dark_sky_status' => 'Florida\'s First Dark Sky Park',
                'description' => '54,000 acres of protected dry prairie offering rare dark southern horizons over the Florida peninsula for planetary and transit viewing.',
            ],
            [
                'name' => 'Grand Canyon National Park',
                'slug' => 'grand-canyon-national-park',
                'country' => 'United States',
                'region' => 'Arizona',
                'latitude' => 36.0544,
                'longitude' => -112.1401,
                'elevation' => 2130,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'World-famous geological wonder with stunning canyon-rim night sky panoramas along Desert View and Mather Point.',
            ],
            [
                'name' => 'Bryce Canyon National Park',
                'slug' => 'bryce-canyon-national-park',
                'country' => 'United States',
                'region' => 'Utah',
                'latitude' => 37.5930,
                'longitude' => -112.1871,
                'elevation' => 2440,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'High-elevation amphitheater of bizarre red rock hoodoos under skies where up to 7,500 stars can be seen with the naked eye.',
            ],
            [
                'name' => 'Arches National Park',
                'slug' => 'arches-national-park',
                'country' => 'United States',
                'region' => 'Utah',
                'latitude' => 38.7331,
                'longitude' => -109.5925,
                'elevation' => 1550,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Over 2,000 natural sandstone arches with world-renowned astrophotography backdrops at Delicate Arch and Windows Section.',
            ],
            [
                'name' => 'Black Canyon of the Gunnison National Park',
                'slug' => 'black-canyon-of-the-gunnison',
                'country' => 'United States',
                'region' => 'Colorado',
                'latitude' => 38.5754,
                'longitude' => -107.7416,
                'elevation' => 2500,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Steep, dramatic sheer granite cliffs carved over 2 million years, providing dark sky viewing high above western Colorado.',
            ],
            [
                'name' => 'Copper Harbor & Keweenaw Dark Sky Park',
                'slug' => 'keweenaw-dark-sky-park',
                'country' => 'United States',
                'region' => 'Michigan (Upper Peninsula)',
                'latitude' => 47.4680,
                'longitude' => -87.8880,
                'elevation' => 250,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'The tip of the Keweenaw Peninsula jutting into Lake Superior, providing pitch-black northern skies ideal for auroras.',
            ],
            [
                'name' => 'Chaco Culture National Historical Park',
                'slug' => 'chaco-culture-national-historical-park',
                'country' => 'United States',
                'region' => 'New Mexico',
                'latitude' => 36.0600,
                'longitude' => -107.9700,
                'elevation' => 1890,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'Ancestral Puebloan ceremonial center aligned with astronomical alignments and solstices, featuring its own public observatory.',
            ],
            [
                'name' => 'Badlands National Park',
                'slug' => 'badlands-national-park',
                'country' => 'United States',
                'region' => 'South Dakota',
                'latitude' => 43.8554,
                'longitude' => -102.3397,
                'elevation' => 950,
                'bortle_class' => 2,
                'dark_sky_status' => 'Pristine Prairie Dark Sky',
                'description' => 'Striking eroded clay buttes, pinnacles, and spires rising out of the Great Plains under sweeping Milky Way skies.',
            ],
            [
                'name' => 'Capitol Reef National Park',
                'slug' => 'capitol-reef-national-park',
                'country' => 'United States',
                'region' => 'Utah',
                'latitude' => 38.3670,
                'longitude' => -111.2615,
                'elevation' => 1700,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'The Waterpocket Fold monocline wrinkle in the earth\'s crust, offering exceptionally pristine Utah desert nightscapes.',
            ],
            [
                'name' => 'Canyonlands National Park (Island in the Sky)',
                'slug' => 'canyonlands-national-park',
                'country' => 'United States',
                'region' => 'Utah',
                'latitude' => 38.3269,
                'longitude' => -109.8783,
                'elevation' => 1800,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Park',
                'description' => 'Vast canyons carved by the Colorado and Green rivers beneath Mesa Arch, one of the premier night photography locations on earth.',
            ],
            [
                'name' => 'Tonopah Stargazing Park',
                'slug' => 'tonopah-stargazing-park',
                'country' => 'United States',
                'region' => 'Nevada',
                'latitude' => 38.0692,
                'longitude' => -117.2306,
                'elevation' => 1840,
                'bortle_class' => 1,
                'dark_sky_status' => 'Ranked #1 Stargazing Destination in North America',
                'description' => 'Consistently rated the #1 stargazing destination in North America by USA Today, with specialized concrete telescope pads.',
            ],
            [
                'name' => 'Glacier National Park (Waterton-Glacier)',
                'slug' => 'glacier-national-park-montana',
                'country' => 'United States',
                'region' => 'Montana',
                'latitude' => 48.7596,
                'longitude' => -113.7870,
                'elevation' => 1500,
                'bortle_class' => 2,
                'dark_sky_status' => 'First Provisional Transboundary Dark Sky Park',
                'description' => 'Glacial peaks and pristine alpine lakes beneath Montana\'s famous "Big Sky", shared across the Canadian border.',
            ],
            [
                'name' => 'Great Sand Dunes National Park',
                'slug' => 'great-sand-dunes',
                'country' => 'United States',
                'region' => 'Colorado',
                'latitude' => 37.7916,
                'longitude' => -105.5943,
                'elevation' => 2500,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'The tallest dunes in North America backed by the rugged Sangre de Cristo Mountains, offering an otherworldly surreal nightscape.',
            ],
            [
                'name' => 'Goblin Valley State Park',
                'slug' => 'goblin-valley-state-park',
                'country' => 'United States',
                'region' => 'Utah',
                'latitude' => 38.5739,
                'longitude' => -110.7061,
                'elevation' => 1520,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Strange mushroom-shaped sandstone hoodoos ("goblins") creating an alien planetary landscape beneath crystal-clear stars.',
            ],
            [
                'name' => 'Buffalo National River',
                'slug' => 'buffalo-national-river',
                'country' => 'United States',
                'region' => 'Arkansas',
                'latitude' => 36.0000,
                'longitude' => -92.7500,
                'elevation' => 250,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'America\'s first national river flowing through the heart of the Ozarks beneath dramatic towering limestone bluffs.',
            ],
            [
                'name' => 'Katahdin Woods and Waters National Monument',
                'slug' => 'katahdin-woods-and-waters',
                'country' => 'United States',
                'region' => 'Maine',
                'latitude' => 45.9700,
                'longitude' => -68.6200,
                'elevation' => 350,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Sanctuary',
                'description' => '87,500 acres of northern Maine North Woods wilderness with exceptional darkness east of the Mississippi River.',
            ],
            [
                'name' => 'Voyageurs National Park',
                'slug' => 'voyageurs-national-park',
                'country' => 'United States',
                'region' => 'Minnesota',
                'latitude' => 48.5000,
                'longitude' => -92.8833,
                'elevation' => 340,
                'bortle_class' => 2,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Maze of interconnected boreal waterways and islands along the US-Canadian border with frequent aurora displays.',
            ],
            [
                'name' => 'Sedona Dark Sky Community',
                'slug' => 'sedona-arizona',
                'country' => 'United States',
                'region' => 'Arizona',
                'latitude' => 34.8697,
                'longitude' => -111.7610,
                'elevation' => 1320,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Community',
                'description' => 'Encircled by towering red sandstone buttes and Cathedral Rock, pioneering strict dark-sky shielding lighting ordinances.',
            ],
            [
                'name' => 'Big Cypress National Preserve',
                'slug' => 'big-cypress-national-preserve',
                'country' => 'United States',
                'region' => 'Florida',
                'latitude' => 25.8589,
                'longitude' => -81.0336,
                'elevation' => 3,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'Subtropical swamp wilderness buffering southern Florida, renowned for unobstructed southern horizon stargazing.',
            ],
            [
                'name' => 'Mammoth Cave National Park',
                'slug' => 'mammoth-cave-national-park',
                'country' => 'United States',
                'region' => 'Kentucky',
                'latitude' => 37.1869,
                'longitude' => -86.1000,
                'elevation' => 220,
                'bortle_class' => 3,
                'dark_sky_status' => 'IDA International Dark Sky Park',
                'description' => 'World\'s longest known cave system underground, protected by lush hardwood forests overhead that keep night skies dark.',
            ],

            // ==================== CANADA (15) ====================
            [
                'name' => 'Jasper National Park',
                'slug' => 'jasper-national-park',
                'country' => 'Canada',
                'region' => 'Alberta',
                'latitude' => 52.8734,
                'longitude' => -118.0814,
                'elevation' => 1060,
                'bortle_class' => 2,
                'dark_sky_status' => 'World\'s Largest Accessible Dark Sky Preserve',
                'description' => '11,000 square kilometers of Canadian Rocky Mountains; host of the annual Jasper Dark Sky Festival beneath glaciated peaks.',
            ],
            [
                'name' => 'Mont-Mégantic Dark Sky Reserve',
                'slug' => 'mont-megantic-reserve',
                'country' => 'Canada',
                'region' => 'Quebec',
                'latitude' => 45.4560,
                'longitude' => -71.1530,
                'elevation' => 1105,
                'bortle_class' => 2,
                'dark_sky_status' => 'First International Dark Sky Reserve (2007)',
                'description' => 'Home to the Observatoire du Mont-Mégantic, pioneering regional light pollution bylaws across 34 surrounding municipalities.',
            ],
            [
                'name' => 'Torrance Barrens Dark-Sky Preserve',
                'slug' => 'torrance-barrens-ontario',
                'country' => 'Canada',
                'region' => 'Ontario (Muskoka)',
                'latitude' => 44.9580,
                'longitude' => -79.5120,
                'elevation' => 250,
                'bortle_class' => 3,
                'dark_sky_status' => 'World\'s First Permanently Designated Dark-Sky Preserve (1999)',
                'description' => 'Canadian Shield granite outcrop and ancient peatlands just two hours north of Toronto, designated in 1999.',
            ],
            [
                'name' => 'Cypress Hills Interprovincial Park',
                'slug' => 'cypress-hills-interprovincial-park',
                'country' => 'Canada',
                'region' => 'Saskatchewan & Alberta',
                'latitude' => 49.6667,
                'longitude' => -109.8333,
                'elevation' => 1466,
                'bortle_class' => 2,
                'dark_sky_status' => 'RASC Dark-Sky Preserve',
                'description' => 'The highest point in Canada between the Rocky Mountains and Labrador, rising high above the surrounding prairie.',
            ],
            [
                'name' => 'Grasslands National Park',
                'slug' => 'grasslands-national-park',
                'country' => 'Canada',
                'region' => 'Saskatchewan',
                'latitude' => 49.2000,
                'longitude' => -107.5000,
                'elevation' => 800,
                'bortle_class' => 1,
                'dark_sky_status' => 'Darkest Dark-Sky Preserve in Canada',
                'description' => 'Canada\'s darkest Dark-Sky Preserve, protecting mixed-grass prairie and badlands where the Milky Way casts visible shadows.',
            ],
            [
                'name' => 'Bruce Peninsula National Park',
                'slug' => 'bruce-peninsula-national-park',
                'country' => 'Canada',
                'region' => 'Ontario',
                'latitude' => 45.2333,
                'longitude' => -81.5167,
                'elevation' => 180,
                'bortle_class' => 2,
                'dark_sky_status' => 'RASC Dark-Sky Preserve',
                'description' => 'Towering limestone cliffs along Georgian Bay surrounded by crystal-clear waters of Lake Huron.',
            ],
            [
                'name' => 'Point Pelee National Park',
                'slug' => 'point-pelee-national-park',
                'country' => 'Canada',
                'region' => 'Ontario',
                'latitude' => 41.9628,
                'longitude' => -82.5186,
                'elevation' => 175,
                'bortle_class' => 4,
                'dark_sky_status' => 'RASC Dark-Sky Preserve',
                'description' => 'The southernmost tip of mainland Canada jutting into Lake Erie, offering rare 360-degree shoreline astronomy.',
            ],
            [
                'name' => 'Wood Buffalo National Park',
                'slug' => 'wood-buffalo-national-park',
                'country' => 'Canada',
                'region' => 'Alberta & Northwest Territories',
                'latitude' => 59.3833,
                'longitude' => -112.9833,
                'elevation' => 200,
                'bortle_class' => 1,
                'dark_sky_status' => 'World\'s Largest Dark-Sky Preserve (44,807 km²)',
                'description' => 'Larger than the country of Switzerland, an immense boreal forest and salt plains preserve with breathtaking aurora activity.',
            ],
            [
                'name' => 'Kejimkujik National Park and National Historic Site',
                'slug' => 'kejimkujik-national-park',
                'country' => 'Canada',
                'region' => 'Nova Scotia',
                'latitude' => 44.4000,
                'longitude' => -65.2000,
                'elevation' => 130,
                'bortle_class' => 2,
                'dark_sky_status' => 'RASC Dark-Sky Preserve',
                'description' => 'Pristine inland lakes and ancient Mi\'kmaw cultural landscape in southwestern Nova Scotia under Bortle 2 skies.',
            ],
            [
                'name' => 'Gordon\'s Park Dark Sky Preserve (Manitoulin Island)',
                'slug' => 'gordons-park-manitoulin',
                'country' => 'Canada',
                'region' => 'Ontario',
                'latitude' => 45.7500,
                'longitude' => -81.9500,
                'elevation' => 190,
                'bortle_class' => 2,
                'dark_sky_status' => 'First Commercial Dark-Sky Preserve in Canada',
                'description' => 'Located on the world\'s largest freshwater island, offering 360-degree viewing and custom observing pads.',
            ],
            [
                'name' => 'Kouchibouguac National Park',
                'slug' => 'kouchibouguac-national-park',
                'country' => 'Canada',
                'region' => 'New Brunswick',
                'latitude' => 46.8500,
                'longitude' => -64.9667,
                'elevation' => 20,
                'bortle_class' => 2,
                'dark_sky_status' => 'RASC Dark-Sky Preserve',
                'description' => 'Coastal barrier islands and tidal lagoons along the Northumberland Strait with dark maritime skies.',
            ],
            [
                'name' => 'Fathom Five National Marine Park',
                'slug' => 'fathom-five-marine-park',
                'country' => 'Canada',
                'region' => 'Ontario',
                'latitude' => 45.3167,
                'longitude' => -81.6500,
                'elevation' => 176,
                'bortle_class' => 2,
                'dark_sky_status' => 'RASC Dark-Sky Preserve',
                'description' => 'Freshwater archipelago of 20 islands preserving historic lighthouses and 22 shipwrecks beneath unpolluted northern skies.',
            ],
            [
                'name' => 'Waterton Lakes National Park',
                'slug' => 'waterton-lakes-national-park',
                'country' => 'Canada',
                'region' => 'Alberta',
                'latitude' => 49.0500,
                'longitude' => -113.9167,
                'elevation' => 1280,
                'bortle_class' => 2,
                'dark_sky_status' => 'International Peace Park Dark-Sky Preserve',
                'description' => 'Where the prairies meet the peaks of the Rockies abruptly, providing dramatic reflections in Upper Waterton Lake.',
            ],
            [
                'name' => 'Bon Accord Dark Sky Community',
                'slug' => 'bon-accord-alberta',
                'country' => 'Canada',
                'region' => 'Alberta',
                'latitude' => 53.8333,
                'longitude' => -113.4167,
                'elevation' => 690,
                'bortle_class' => 3,
                'dark_sky_status' => 'First International Dark Sky Community in Canada',
                'description' => 'Pioneering town in Sturgeon County that passed comprehensive outdoor lighting bylaws to safeguard views of the northern skies.',
            ],
            [
                'name' => 'Beaver Hills Dark Sky Preserve',
                'slug' => 'beaver-hills-dark-sky-preserve',
                'country' => 'Canada',
                'region' => 'Alberta',
                'latitude' => 53.5333,
                'longitude' => -112.8667,
                'elevation' => 710,
                'bortle_class' => 3,
                'dark_sky_status' => 'RASC Dark Sky Preserve (Elk Island)',
                'description' => 'Encompassing Elk Island National Park and Cooking Lake-Blackfoot Provincial Recreation Area just east of Edmonton.',
            ],

            // ==================== GLOBAL ICONIC DARK SKY RESERVES (5) ====================
            [
                'name' => 'Aoraki Mackenzie Dark Sky Reserve',
                'slug' => 'aoraki-mackenzie-reserve',
                'country' => 'New Zealand',
                'region' => 'Canterbury (South Island)',
                'latitude' => -43.9833,
                'longitude' => 170.4500,
                'elevation' => 700,
                'bortle_class' => 1,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Reserve',
                'description' => 'Largest dark sky reserve in the Southern Hemisphere, offering breathtaking views of the Magellanic Clouds and the Southern Cross.',
            ],
            [
                'name' => 'Atacama Desert (San Pedro de Atacama)',
                'slug' => 'atacama-desert-chile',
                'country' => 'Chile',
                'region' => 'Antofagasta',
                'latitude' => -22.9087,
                'longitude' => -68.1997,
                'elevation' => 2400,
                'bortle_class' => 1,
                'dark_sky_status' => 'World Astronomical Capital',
                'description' => 'The driest non-polar desert on Earth with over 330 cloudless nights per year, home to ALMA and Paranal VLT.',
            ],
            [
                'name' => 'NamibRand Nature Reserve',
                'slug' => 'namibrand-nature-reserve',
                'country' => 'Namibia',
                'region' => 'Hardap',
                'latitude' => -24.9667,
                'longitude' => 15.9667,
                'elevation' => 980,
                'bortle_class' => 1,
                'dark_sky_status' => 'IDA Gold Tier Dark Sky Reserve',
                'description' => 'Over 200,000 hectares of Namib desert sand dunes, recognized as having the darkest measured night skies on the African continent.',
            ],
            [
                'name' => 'Warrumbungle National Park',
                'slug' => 'warrumbungle-national-park',
                'country' => 'Australia',
                'region' => 'New South Wales',
                'latitude' => -31.2833,
                'longitude' => 149.0000,
                'elevation' => 800,
                'bortle_class' => 1,
                'dark_sky_status' => 'First International Dark Sky Park in Australia',
                'description' => 'Extinct volcanic peaks adjacent to Siding Spring Observatory, offering crystal-clear vistas of the Galactic Core overhead.',
            ],
            [
                'name' => 'Mauna Kea Observatories',
                'slug' => 'mauna-kea-hawaii',
                'country' => 'United States',
                'region' => 'Hawaii',
                'latitude' => 19.8207,
                'longitude' => -155.4681,
                'elevation' => 4205,
                'bortle_class' => 1,
                'dark_sky_status' => 'Premier Global Astronomical Reserve',
                'description' => 'Dormant volcano rising 13,796 feet above the Pacific Ocean, placing it above 40 percent of Earth\'s atmosphere with unsurpassed seeing.',
            ],
        ];

        foreach ($spots as $spotData) {
            StargazingSpot::updateOrCreate(
                ['slug' => $spotData['slug']],
                $spotData
            );
        }
    }
}
